version: 2.1

jobs:
  test:
    docker:
      - image: florescobar919/scambia-api-web:latest
    steps:
      - checkout
      - run: cd scambia-api && composer install --no-interaction && make test

workflows:
  test_project:
    jobs:
      - test
