version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.2-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Configura el entorno Laravel
      - run:
          name: Set up Laravel
          command: |
            sudo apt-get install -y libzip-dev
            composer install --no-interaction --prefer-dist

      # Ejecuta las pruebas PHPUnit
      - run:
          name: Run PHPUnit Tests
          command: vendor/bin/phpunit

# Configuración adicional según sea necesario