services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:80" 
    depends_on:
     - db
    volumes:
      - .:/var/www/html
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: scambia-db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    ports:
      - "3310:3306"
