/*pipeline {
    agent any
    environment {
        // Definir variables de entorno si es necesario
        APP_ENV = 'production'
    }

    stages {

        stage('Ejecutar Pruebas') {
            environment {
                // Definir la variable de entorno para el ejecutable make
                PATH = "C:\\MinGW\\bin\\:${env.PATH}"
            }
            steps {
                // Ejecutar pruebas PHPUnit utilizando el ejecutable 'make' definido en el PATH
                bat 'cd scambia-api && make test'
            }
        }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Instalar Composer') {
            steps {
                // Instalar Composer globalmente
                script {
                    def composerHome = tool 'Composer'
                    env.PATH = "${composerHome}/bin:${env.PATH}"
                    sh 'composer --version'
                }
            }
        }

        stage('Instalar Dependencias') {
            steps {
                // Instalar dependencias de Laravel usando Composer
                sh 'composer install --no-interaction --prefer-dist'
            }
        }

        stage('Test') {
            steps {
                script {
                    bat 'make test'
                }
            }
        }
    }
}*/

pipeline {
    agent any
    stages {
        stage('Clonar Repositorio') {
            steps {
                // Clonar el repositorio desde tu sistema de control de versiones
                git 'https://github.com/florescobar/Scambia-PracticasCC-UGR.git'
            }
        }
        stage('Instalar Composer y Dependencias') {
            steps {
                // Descargar e instalar Composer
                bat '''
                    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
                    php -r "if (hash_file('sha384', 'composer-setup.php') === 'EXPECTED_HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
                    php composer-setup.php
                    php -r "unlink('composer-setup.php');"
                '''

                // Configurar la herramienta Composer
                env.PATH = "${WORKSPACE}/composer:${env.PATH}"

                // Instalar dependencias de Laravel usando Composer
                bat 'php composer.phar install --no-interaction --prefer-dist'
            }
        }

        stage('Configuración de Entorno') {
            steps {
                // Copiar el archivo de configuración de ejemplo y configurar variables de entorno
                bat 'cp .env.example .env'
                bat'php artisan key:generate'
                // Configurar otras variables de entorno si es necesario
            }
        }

        stage('Ejecutar Pruebas') {
            steps {
                // Ejecutar pruebas PHPUnit
                sh 'php artisan test'
            }
        }
    }
}
