/*pipeline {
    agent any
    environment {
        // Definir variables de entorno si es necesario
        APP_ENV = 'production'
    }

    stages {

        stage('Ejecutar Pruebas') {
            environment {
                // Definir la variable de entorno para el ejecutable make
                PATH = "C:\\MinGW\\bin\\:${env.PATH}"
            }
            steps {
                // Ejecutar pruebas PHPUnit utilizando el ejecutable 'make' definido en el PATH
                bat 'cd scambia-api && make test'
            }
        }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Instalar Composer') {
            steps {
                // Instalar Composer globalmente
                script {
                    def composerHome = tool 'Composer'
                    env.PATH = "${composerHome}/bin:${env.PATH}"
                    sh 'composer --version'
                }
            }
        }

        stage('Instalar Dependencias') {
            steps {
                // Instalar dependencias de Laravel usando Composer
                sh 'composer install --no-interaction --prefer-dist'
            }
        }

        stage('Test') {
            steps {
                script {
                    bat 'make test'
                }
            }
        }
    }
}*/

pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                git 'https://github.com/florescobar/Scambia-PracticasCC-UGR.git'
                bat 'composer install'
                bat 'cp .env.example .env'
                bat 'php artisan key:generate'
            }
        }
        stage('Test') {
            steps {
                bat './vendor/bin/phpunit'
            }
        }
    }
}